---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: unir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{acr_name}}/redis:latest"
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes: 
      - name: storage
        persistentVolumeClaim:
          claimName: webserver-pvc


