apiVersion: v1
kind: PersistentVolume
metadata:
  name: webserver-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  storageClassName: local-storage  # Vinculo el PC y PVC
  nfs:  
    server: 192.168.1.100
    path: /data
  